# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
     - release/*
     - workshop/*
    exclude:
     - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'

- script: |
    npm i -g @antora/cli@2.0 &&\
    npm i @antora/site-generator-default@2.0
  displayName: 'Install Antora'

- script: |
    antora --pull --stacktrace site.yml
  displayName: 'Build Docs'